import { GlossaryTerm } from '../../types';

export const CAT1_CONCEPTS_TERMS: GlossaryTerm[] = [
  {
    id: 'database',
    termFr: 'Base de données (Database)',
    termEn: 'Database',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Ensemble structuré et organisé de données stockées électroniquement dans un système informatique, géré de manière centralisée.',
    shortDefEn: 'A structured collection of electronically stored data, managed centrally through a database engine.',
    fullExplanationFr: 'Une base de données est un conteneur logique rassemblant des tables, des index, des vues et d\'autres objets structurés. Elle permet d\'assurer la persistance, la sécurité, l\'intégrité et la disponibilité des données. Dans une architecture client-serveur, une instance de SGBD peut héberger une ou plusieurs bases de données indépendantes.',
    fullExplanationEn: 'A database is a logical container holding tables, indexes, views, and schemas. It ensures data persistence, transactional safety, access control, and high availability across user sessions.',
    codeSnippet: `-- Création d'une base de données standard
CREATE DATABASE e_commerce_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

-- Connexion ou sélection de la base de données
USE e_commerce_db;`,
    codeSnippetCommentFr: 'Création standard d\'une base de données avec encodage universel UTF-8.',
    codeSnippetCommentEn: 'Standard database creation using universal UTF-8 character encoding.',
    dialects: {
      universal: false,
      postgres: 'CREATE DATABASE nom_db WITH ENCODING = \'UTF8\'; (En PostgreSQL, on se connecte via \\c nom_db ou dans la chaîne de connexion).',
      mysql: 'CREATE DATABASE IF NOT EXISTS nom_db; puis USE nom_db;',
      sqlServer: 'CREATE DATABASE nom_db; puis USE nom_db;',
      oracle: 'En Oracle 12c+, la notion équivalente est la PDB (Pluggable Database) au sein d\'une CDB (Container Database) : ALTER SESSION SET CONTAINER = pdb1;',
      specialNoteFr: 'Sous MySQL, SCHEMA et DATABASE sont de stricts synonymes. Sous Oracle et SQL Server, un Schéma est un espace de noms associé à un utilisateur au sein d\'une base.',
    },
    crossReferences: [
      { id: 'sgbd', labelFr: 'SGBD (DBMS)', labelEn: 'DBMS' },
      { id: 'schema', labelFr: 'Schéma (Schema)', labelEn: 'Schema' },
      { id: 'table', labelFr: 'Table', labelEn: 'Table' },
    ],
    tags: ['Architecture', 'Stockage', 'Fondamentaux'],
    difficulty: 'beginner',
    audience: ['beginner', 'developer', 'data_analyst'],
    proTipFr: 'Toujours spécifier un jeu de caractères unicode moderne (utf8mb4 / UTF-8) dès la création de la base pour éviter les corruptions d\'emojis et de caractères accentués.',
    proTipEn: 'Always specify modern utf8mb4 / UTF-8 encoding during database creation to prevent emoji and accent corruption.',
  },
  {
    id: 'table',
    termFr: 'Table',
    termEn: 'Table',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Structure de base d\'une base de données relationnelle, organisée sous forme de grille bidimensionnelle composée de colonnes et de lignes.',
    shortDefEn: 'The core foundational structure of a relational database, arranged as a 2D matrix of typed columns and record rows.',
    fullExplanationFr: 'Une table (ou relation au sens du modèle d\'Edgar F. Codd) stocke des entités homogènes (par exemple des clients, des produits ou des commandes). Chaque table possède un nom unique dans son schéma, une liste de colonnes rigoureusement typées, et contient zéro ou plusieurs lignes (tuples).',
    fullExplanationEn: 'A table represents an entity type (e.g., customers, orders). Each table has a unique name in its schema, typed attributes (columns), and contains zero or more records (rows/tuples).',
    codeSnippet: `CREATE TABLE clients (
  client_id INT NOT NULL,
  nom VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  date_inscription DATE DEFAULT CURRENT_DATE,
  CONSTRAINT pk_clients PRIMARY KEY (client_id),
  CONSTRAINT uq_clients_email UNIQUE (email)
);`,
    codeSnippetCommentFr: 'Définition d\'une table relationnelle avec colonnes typées et contraintes.',
    codeSnippetCommentEn: 'Relational table declaration with typed columns and structural constraints.',
    dialects: {
      universal: true,
      postgres: 'Types courants : SERIAL, BIGSERIAL ou GENERATED ALWAYS AS IDENTITY.',
      mysql: 'Clause auto_increment : client_id INT AUTO_INCREMENT PRIMARY KEY.',
      sqlServer: 'Clause IDENTITY : client_id INT IDENTITY(1,1) PRIMARY KEY.',
      oracle: 'Clause IDENTITY (12c+) : client_id NUMBER GENERATED BY DEFAULT AS IDENTITY.',
      specialNoteFr: 'La syntaxe de base CREATE TABLE est standardisée ANSI SQL, mais les colonnes auto-incrémentées varient selon le SGBD.',
    },
    crossReferences: [
      { id: 'colonne', labelFr: 'Colonne (Champ)', labelEn: 'Column' },
      { id: 'ligne', labelFr: 'Ligne (Tuple)', labelEn: 'Row (Tuple)' },
      { id: 'primary-key', labelFr: 'Clé primaire (PK)', labelEn: 'Primary Key' },
    ],
    tags: ['Relationnel', 'Structure', 'DDL'],
    difficulty: 'beginner',
    audience: ['beginner', 'developer', 'data_analyst'],
    proTipFr: 'Nommez vos tables au pluriel ou au singulier selon une convention d\'équipe uniforme (ex: `clients` ou `client`), mais restez 100% cohérent dans tout le schéma.',
    proTipEn: 'Choose a consistent plural or singular naming convention (e.g., `customers` vs `customer`) and enforce it throughout your schema.',
  },
  {
    id: 'colonne',
    termFr: 'Colonne (Champ / Attribut)',
    termEn: 'Column (Field / Attribute)',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Attribut vertical spécifique d\'une table, caractérisé par un nom, un type de données (INT, VARCHAR, DATE) et d\'éventuelles contraintes.',
    shortDefEn: 'A vertical component of a table holding a specific attribute with a defined data type and optional constraints.',
    fullExplanationFr: 'Une colonne représente une propriété descriptive de l\'entité stockée. Elle impose un domaine de valeurs strict grâce à son type de données et des règles de validation (NULL/NOT NULL, CHECK, DEFAULT). Dans le modèle relationnel théorique, les colonnes sont désignées sous le nom d\'attributs.',
    fullExplanationEn: 'A column represents an entity property. It defines an attribute domain with strict data types, precision, and constraints (NOT NULL, CHECK, DEFAULT).',
    codeSnippet: `-- Ajout d'une colonne avec contrainte et valeur par défaut
ALTER TABLE clients 
  ADD statut VARCHAR(20) DEFAULT 'actif' NOT NULL;

-- Modification d'une colonne existante
ALTER TABLE clients 
  MODIFY email VARCHAR(150) NOT NULL; -- Syntaxe MySQL / Oracle`,
    codeSnippetCommentFr: 'Ajout et modification de colonnes dans une table existante.',
    codeSnippetCommentEn: 'Adding and altering table columns in an existing table.',
    dialects: {
      universal: false,
      postgres: 'ALTER TABLE clients ALTER COLUMN email TYPE VARCHAR(150);',
      mysql: 'ALTER TABLE clients MODIFY COLUMN email VARCHAR(150) NOT NULL;',
      sqlServer: 'ALTER TABLE clients ALTER COLUMN email VARCHAR(150) NOT NULL;',
      oracle: 'ALTER TABLE clients MODIFY (email VARCHAR2(150) NOT NULL);',
    },
    crossReferences: [
      { id: 'table', labelFr: 'Table', labelEn: 'Table' },
      { id: 'types-donnees', labelFr: 'Types de données', labelEn: 'Data Types' },
      { id: 'not-null', labelFr: 'Contrainte NOT NULL', labelEn: 'NOT NULL' },
    ],
    tags: ['Schéma', 'Attribut', 'Typage'],
    difficulty: 'beginner',
    audience: ['beginner', 'developer', 'data_analyst'],
    proTipFr: 'Évitez d\'utiliser des mots réservés du SQL comme noms de colonnes (ex: `order`, `date`, `user`, `group`), sous peine d\'exiger des délimiteurs ou guillemets complexes.',
    proTipEn: 'Avoid naming columns after SQL reserved keywords (e.g. `order`, `user`, `date`), which require awkward dialect-specific quoting.',
  },
  {
    id: 'ligne',
    termFr: 'Ligne (Enregistrement / Tuple)',
    termEn: 'Row (Record / Tuple)',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Entrée horizontale unique dans une table, représentant une instance concrète de l\'entité avec ses valeurs associées.',
    shortDefEn: 'A single horizontal record in a table representing an individual entity instance with its related values.',
    fullExplanationFr: 'Une ligne regroupe l\'ensemble des valeurs correspondant aux différentes colonnes pour une entité précise. En théorie relationnelle, elle est appelée tuple. Une ligne doit obligatoirement pouvoir être distinguée de toutes les autres grâce à une clé primaire.',
    fullExplanationEn: 'A row represents a single structured entity instance. In relational relational calculus, it is called a tuple. Each row must be uniquely identifiable via a primary key.',
    codeSnippet: `-- Insertion d'une ligne unique (tuple)
INSERT INTO clients (client_id, nom, email, date_inscription)
VALUES (101, 'Ada Lovelace', 'ada@computing.org', '2024-01-15');

-- Consultation de la ligne
SELECT * FROM clients WHERE client_id = 101;`,
    codeSnippetCommentFr: 'Insertion d\'un nouvel enregistrement et sélection ciblée par clé.',
    codeSnippetCommentEn: 'Single row insert followed by indexed key lookup.',
    dialects: {
      universal: true,
      postgres: 'Prend en charge la clause RETURNING pour renvoyer la ligne insérée.',
      mysql: 'Prend en charge INSERT ... ON DUPLICATE KEY UPDATE.',
      sqlServer: 'Prend en charge la clause OUTPUT pour capturer la ligne créée.',
      oracle: 'Prend en charge la clause RETURNING INTO en PL/SQL.',
    },
    crossReferences: [
      { id: 'table', labelFr: 'Table', labelEn: 'Table' },
      { id: 'colonne', labelFr: 'Colonne', labelEn: 'Column' },
      { id: 'primary-key', labelFr: 'Clé primaire (PK)', labelEn: 'Primary Key' },
    ],
    tags: ['Tuple', 'Enregistrement', 'DML'],
    difficulty: 'beginner',
    audience: ['beginner', 'developer', 'data_analyst'],
    proTipFr: 'En SQL, l\'ordre physique de stockage des lignes dans une table n\'est jamais garanti. Pour obtenir un ordre déterminé, vous devez toujours ajouter une clause ORDER BY.',
    proTipEn: 'Physical row storage is inherently unordered in relational tables. Always explicitly append ORDER BY whenever deterministic ordering is required.',
  },
  {
    id: 'schema',
    termFr: 'Schéma (Schema)',
    termEn: 'Schema',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Regroupement logique d\'objets de base de données (tables, vues, fonctions, index) appartenant généralement à un propriétaire ou un domaine fonctionnel.',
    shortDefEn: 'A logical namespace grouping database objects (tables, views, routines, indexes) under a specific owner or domain.',
    fullExplanationFr: 'Le schéma sert d\'espace de noms (namespace). Il permet de séparer les modules d\'une application (ex: `ventes.commandes`, `rh.employes`) ou d\'isoler les locataires dans une architecture multi-tenant. La qualification complète d\'un objet s\'écrit souvent `nom_base.nom_schema.nom_table`.',
    fullExplanationEn: 'A schema acts as a logical namespace within a database, segregating functional areas or security boundaries (e.g., `sales.orders`, `hr.employees`).',
    codeSnippet: `-- Création d'un schéma dédié à la facturation
CREATE SCHEMA facturation;

-- Création d'une table qualifiée dans ce schéma
CREATE TABLE facturation.factures (
  facture_id INT PRIMARY KEY,
  montant_ht DECIMAL(10, 2) NOT NULL,
  date_emission DATE NOT NULL
);`,
    codeSnippetCommentFr: 'Création d\'un espace de noms logique et d\'une table qualifiée.',
    codeSnippetCommentEn: 'Creating a logical namespace and table referencing that schema.',
    dialects: {
      universal: false,
      postgres: 'Schéma par défaut = `public`. Configuration du chemin : `SET search_path TO facturation, public;`',
      sqlServer: 'Schéma par défaut = `dbo`. Syntaxe complète : `CREATE SCHEMA facturation AUTHORIZATION dbo;`',
      oracle: 'En Oracle, un SCHEMA est intrinsèquement lié à un compte utilisateur : créer un utilisateur `CREATE USER facturation ...` crée son schéma éponyme.',
      mysql: 'Sous MySQL, `CREATE SCHEMA` est un alias strict de `CREATE DATABASE`. Il n\'y a pas de notion de sous-schéma dans une base MySQL.',
      specialNoteFr: 'Distinction cruciale : sous Postgres/SQL Server, 1 Base = N Schémas. Sous MySQL, 1 Schéma = 1 Base.',
    },
    crossReferences: [
      { id: 'database', labelFr: 'Base de données', labelEn: 'Database' },
      { id: 'table', labelFr: 'Table', labelEn: 'Table' },
      { id: 'sgbd', labelFr: 'SGBD (DBMS)', labelEn: 'DBMS' },
    ],
    tags: ['Namespace', 'Architecture', 'Sécurité'],
    difficulty: 'intermediate',
    audience: ['developer', 'data_analyst'],
    proTipFr: 'Utilisez les schémas pour séparer les données brutes (staging), nettoyées (core/ods) et de reporting (marts/bi) dans les architectures data warehouse.',
    proTipEn: 'Leverage schemas to segment raw ingestion staging, transformed core data, and reporting data marts in analytics pipelines.',
  },
  {
    id: 'sgbd',
    termFr: 'SGBD (Système de Gestion de Base de Données / DBMS)',
    termEn: 'DBMS (Database Management System)',
    category: 1,
    categoryNameFr: 'Concepts fondamentaux des bases de données',
    categoryNameEn: 'Database Core Concepts',
    shortDefFr: 'Ensemble logiciel permettant de définir, stocker, manipuler, sécuriser et interroger des bases de données.',
    shortDefEn: 'System software for creating, managing, querying, securing, and tuning structured databases.',
    fullExplanationFr: 'Un SGBD (ou RDBMS pour les systèmes relationnels) gère l\'accès concurrentiel aux données, l\'exécution optimisée des requêtes SQL, la journalisation (Write-Ahead Logging / Redo Log), la sécurité, la sauvegarde et la reprise après sinistre. Les moteurs relationnels majeurs sont PostgreSQL, MySQL, Microsoft SQL Server et Oracle Database.',
    fullExplanationEn: 'A DBMS executes query parsing, cost-based optimization, transaction write-ahead logging (WAL), concurrency arbitration (MVCC/locking), caching, and backup recovery.',
    codeSnippet: `-- Vérifier la version et le moteur SGBD actif
-- PostgreSQL :
SELECT version();

-- MySQL :
SELECT VERSION(), @@version_comment;

-- SQL Server (T-SQL) :
SELECT @@VERSION;

-- Oracle :
SELECT banner FROM v$version WHERE ROWNUM = 1;`,
    codeSnippetCommentFr: 'Requêtes de métadonnées pour inspecter le moteur SGBD connecté.',
    codeSnippetCommentEn: 'Metadata queries retrieving engine version and runtime environment.',
    dialects: {
      universal: false,
      postgres: 'Moteur open source mondial réputé pour sa conformité ANSI SQL, ses types JSONB et ses extensions (PostGIS).',
      mysql: 'Moteur open source populaire avec architecture de stockage modulaire (InnoDB par défaut).',
      sqlServer: 'SGBD d\'entreprise Microsoft avec dialecte T-SQL, intégration Active Directory et outillage SSMS.',
      oracle: 'Leader historique d\'entreprise avec dialecte PL/SQL, RAC (Real Application Clusters) et fonctionnalités avancées.',
    },
    crossReferences: [
      { id: 'database', labelFr: 'Base de données', labelEn: 'Database' },
      { id: 'acid', labelFr: 'Propriétés ACID', labelEn: 'ACID Properties' },
      { id: 'transaction', labelFr: 'Transaction', labelEn: 'Transaction' },
    ],
    tags: ['Moteur', 'Serveur', 'Logiciel'],
    difficulty: 'beginner',
    audience: ['beginner', 'developer', 'data_analyst'],
    proTipFr: 'Bien que le langage SQL soit normalisé par l\'ANSI/ISO, chaque SGBD implémente des extensions propriétaires et optimise ses plans d\'exécution différemment.',
    proTipEn: 'While SQL has ANSI/ISO standards, each database engine provides proprietary dialect extensions and independent cost-based optimizers.',
  },
];
